[package]
edition = "2021"
name = "imranbarbhuiya_img-hasher"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.13.3", default-features = false, features = [
    "napi4",
    "async",
] }
napi-derive = "2.13.0"
image_hasher = "1.2.0"
image = "0.24.7"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.33.0", features = ["full"] }

[target.x86_64-unknown-linux-gnu.dependencies]
openssl-sys = { version = "0.9.93", features = ["vendored"] }

[target.x86_64-unknown-linux-musl.dependencies]
openssl-sys = { version = "0.9.93", features = ["vendored"] }


[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
